[package]
name = "Http_Exer1"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
reqwest = { version = "0.12.23", features = ["blocking"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }



