[package]
name = "Axum_course"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
hyper = "1"
uuid = { version = "1.18.1", features = ["v4"] }
serde = { version = "1.0.227", features = ["derive"] }

