[package]
name = "intoasync"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
serde = { version = "1.0.219", features = ["derive"] }
tokio = {version = "1.46.1", features = ["full"]} 
tower-http = { version = "0.6.6", features = ["fs"] }
