[package]
name = "Recap"
version = "0.1.0"
edition = "2024"

[dependencies]
error = "0.1.9"
json = "0.12.4"
reqwest = { version = "0.12.23", features = ["json"] }
serde = "1.0.224"
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }
