[package]
name = "Test_3"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
dotenvy = "0.15.7"
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "macros"] }
tokio = { version = "1.47.1", features = ["full"] }
